print(all([True]))
print(all([True, True]))
print(all([True, True, False]))
print(all([1, 2, 3]))
print(all([1, 2, 3, 0 ]))
print(all(["a", "b"]))
print(all(["a", "b", ""]))
print(all([]))

print(any([True]))
print(any([True, True]))
print(any([False, False]))
print(any([True, True, False]))
print(any([1, 2, 3]))
print(any([1, 2, 3, 0]))
print(any([0]))
print(any(["a", "b"]))
print(any(["a", "b", ""]))
print(any([""]))
print(any([]))